---
- hosts: 127.0.0.1

  vars:

    # The following vars must be supplied by the caller:
    # app

  tasks:

  - name: Start app
    action: "shell /sbin/start ${app}"
    only_if: 'os.path.isfile("/etc/init/$app.conf")'
