#!/usr/bin/python

import json
import re
import os
import lockfile
import tempfile
import shutil
from subprocess import call, Popen, PIPE, STDOUT
import zipfile
import boto
from boto.s3.key import Key


def latest_release(s3_bucket):
  releases = s3_bucket.list()
  latest_release_number = -1
  for key in releases:
    match = re.match(r'^release-([0-9]+)/', key.name)
    if match:
      release_number = int(match.group(1))
      if release_number > latest_release_number:
        latest_release_number = release_number

  return latest_release_number


def copy_app(project, app, s3_bucket, release_name):
  release_download_base_dir = '/opt/%s/%s/releases' % (project, app)
  release_download_dir = release_download_base_dir + '/' + release_name
  changed = False
  if not os.path.isdir(release_download_dir):
    changed = True
    os.makedirs(release_download_dir)

  for key in s3_bucket.list(prefix = '%s/%s' % (release_name, app)):
    release_file = key.name
    file_key = Key(s3_bucket)
    file_key.key = release_file
    dest_file = release_download_base_dir + '/' + release_file
    if not os.path.isfile(dest_file):
      changed = True
      file_key.get_contents_to_filename(dest_file)

    if release_file.endswith('.zip'):
      app_version = re.match(r'.*/%s-(.+).zip' % app, release_file).group(1)

  if changed:
    run_ansible_playbook('install-app.yaml', "project=%s app=%s src='%s' version='%s'" % (project, app, release_download_dir, app_version))

  return changed


def install_prereqs(project, app):
  app_dir = '/opt/%s/%s/current' % (project, app)
  check_for_ruby(app_dir)
  check_for_java(app_dir)
  check_for_gemfile(app, app_dir)

  #check_for_procfile()


def check_for_ruby(base_dir):
  ruby_version = find_and_read_version_file(base_dir, '.rbenv-version')
  if ruby_version:
    rbenv_home = '/usr/local/rbenv'
    run_ansible_playbook('install-ruby.yaml', "version='%s' rbenv_home=%s" % (ruby_version, rbenv_home))
    os.environ['RBENV_ROOT'] = rbenv_home
    os.environ['PATH'] = rbenv_home + '/shims' + os.pathsep + rbenv_home + '/bin' + os.pathsep + os.environ['PATH']


def check_for_java(base_dir):
  java_version = find_and_read_version_file(base_dir, '.java-version')
  if java_version:
    run_ansible_playbook('install-java.yaml', "version='%s'" % java_version)


def check_for_gemfile(app, base_dir):
  for root, dirs, files in os.walk(base_dir, followlinks = True):
    if 'Gemfile' in files:
      run_ansible_playbook('bundle-install.yaml', "app='%s' gemfile_dir='%s'" % (app, root))
      break


def find_and_read_version_file(base_dir, filename):
  version = None
  for root, dirs, files in os.walk(base_dir, followlinks = True):
    if filename in files:
      found = True
      with open(root + '/' + filename) as f:
        version = f.read().strip()
      break

  return version


def run_ansible_playbook(playbook_name, extra_vars):
  ansible_command_line = 'ansible-playbook -v -c local -e "%s" %s' % (extra_vars, playbook_name)
  p = Popen(ansible_command_line, shell = True, stdin = PIPE, stdout = PIPE, stderr = PIPE, close_fds = True)
  p.wait()
  command_output = p.stdout.read() + ', ' + p.stderr.read()
  return_code = p.returncode
  if return_code != 0:
    raise RuntimeError("Ansible playbook " + playbook_name + " returned " + str(return_code) + ': ' + command_output)


def main():
  module = AnsibleModule(
    argument_spec = dict(
      project = dict(required = True),
      app = dict(required = True),
      bucket = dict(required = True)
    )
  )

  project = module.params['project']
  app = module.params['app']
  bucket = module.params['bucket']

  changed = False

  try:

    conn = boto.connect_s3()
    s3_bucket = conn.get_bucket(bucket)

    release_num = latest_release(s3_bucket)
    if release_num > 0:
      changed = copy_app(project, app, s3_bucket, 'release-' + str(release_num))

    if changed:
      install_prereqs(project, app)
      # stop_app()
      # install_app()
      # start_app()

  except Exception, e:
    module.fail_json(msg = str(e))
    #raise e

  module.exit_json(changed = changed)


# include magic from lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>

lock = lockfile.FileLock('/var/run/zerobot-deploy')
if not lock.is_locked():
  with lock:
    main()
